* регулярные выражения
* Словари
* list comprehentions
* Возможно функции

Ссылки на почитать по регуляркам:
* https://www.exlab.net/files/tools/sheets/regexp/regexp.pdf
    
* https://habr.com/ru/post/115825/
        
* https://habr.com/ru/post/115436/

In [ ]:
import re

re.findall
re.compile
re.sub
re.search
re.finditer
re.match

In [ ]:
dct = {key:value}

In [13]:
import json

In [15]:
import csv

csv - , (c - comma)
tsv - \t (t - tab)

<hr>
Есть выгрузка из ведомости сотрудников по выполненным работам для расчета дохода - <a href='https://clck.ru/dX8tT'>https://clck.ru/dX8tT</a>
<p>Посчитать сколько денег мы им должны. </p>

In [ ]:
import csv

def tax(salary, proc = 13):
    for key in salary.keys():
        salary[key] = salary[key] * (1 - proc / 100)
    return(salary)


salary = {}
with open('employee_salary.csv', newline='') as csvfile:
    reader = csv.DictReader(csvfile, delimiter = '\t')
    for line in reader:
        salary[line['employeeId']] = salary.get(line['employeeId'], 0) + int(line['value'])
print(tax(salary))

In [ ]:
if line['employeeId'] in salary:
    salary[line['employeeId']] += int(line['value'])
else:
    salary[line['employeeId']] = int(line['value'])

Доп. условие - вычесть 13% из каждой суммы (эмуляция уплаты налога) (доп доп условие - написать функцию и процент передавать параметром, по умолчанию 13%)

<hr>

Открыть любую тетрадку с лекции (она будет валидным json - например, https://clck.ru/dX8vK ) и создать лист, состоящий только из кода

In [10]:
import json

with open('9 - Функции - СТАРАЯ ДЛЯ ЗАДАНИЯ.ipynb', 'r', encoding = 'utf-8') as file:
    workbook = json.load(file)
lst = []
for i in workbook['cells']:
    if i['cell_type'] == 'code':
        lst += [i['source']]
lst[:5]

[["name = 'Вася'\n",
  '\n',
  'def foo():\n',
  "    name = 'Петр'\n",
  '    print(name)\n',
  ' \n',
  'foo()\n',
  'print(name)'],
 ["name = 'Вася'\n",
  '\n',
  'def foo():\n',
  '    global name\n',
  "    name = 'Петр'\n",
  '    print(name)\n',
  ' \n',
  'foo()\n',
  'print(name)'],
 ['i = 5\n', 'if i > 6:\n', "    print('dada')"],
 ['i > 6'],
 ['# Тут можно убрать один return и немного переписать код - как?\n',
  'def odd_or_even(lst, odd = True):\n',
  '    tmp_res = []\n',
  '    if odd == False:\n',
  '        for item in lst:\n',
  '            if item % 2 == 0:\n',
  '                tmp_res.append(item)\n',
  '        return tmp_res\n',
  '    else:\n',
  '        for item in lst:\n',
  '            if item % 2 != 0:\n',
  '                tmp_res.append(item)\n',
  '        return tmp_res']]

In [9]:
workbook

{'cells': [{'cell_type': 'markdown',
   'id': 'c4111e3a',
   'metadata': {},
   'source': ['## Функции - продолжение']},
  {'cell_type': 'markdown',
   'id': '0c506a67',
   'metadata': {},
   'source': ['### Локальные и глобальные переменные']},
  {'cell_type': 'code',
   'execution_count': 10,
   'id': 'f820cf38',
   'metadata': {},
   'outputs': [{'name': 'stdout',
     'output_type': 'stream',
     'text': ['Петр\n', 'Вася\n']}],
   'source': ["name = 'Вася'\n",
    '\n',
    'def foo():\n',
    "    name = 'Петр'\n",
    '    print(name)\n',
    ' \n',
    'foo()\n',
    'print(name)']},
  {'cell_type': 'code',
   'execution_count': 13,
   'id': '42757cdf',
   'metadata': {},
   'outputs': [{'name': 'stdout',
     'output_type': 'stream',
     'text': ['Петр\n', 'Петр\n']}],
   'source': ["name = 'Вася'\n",
    '\n',
    'def foo():\n',
    '    global name\n',
    "    name = 'Петр'\n",
    '    print(name)\n',
    ' \n',
    'foo()\n',
    'print(name)']},
  {'cell_type': 'markdown',
   'id': 'f71ddefc',
   'metadata': {},
   'source': ['Global переназначает видимость переменной с локальной (внутри функции) до глобальной видимости']},
  {'cell_type': 'markdown',
   'id': 'aa17f373',
   'metadata': {},
   'source': ['### Значения по умолчанию']},
  {'cell_type': 'code',
   'execution_count': 19,
   'id': 'fa1543f5',
   'metadata': {},
   'outputs': [],
   'source': ['i = 5\n', 'if i > 6:\n', "    print('dada')"]},
  {'cell_type': 'code',
   'execution_count': 20,
   'id': '2e8d19af',
   'metadata': {},
   'outputs': [{'data': {'text/plain': ['False']},
     'execution_count': 20,
     'metadata': {},
     'output_type': 'execute_result'}],
   'source': ['i > 6']},
  {'cell_type': 'code',
   'execution_count': 14,
   'id': '694b0f58',
   'metadata': {},
   'outputs': [],
   'source': ['# Тут можно убрать один return и немного переписать код - как?\n',
    'def odd_or_even(lst, odd = True):\n',
    '    tmp_res = []\n',
    '    if odd == False:\n',
    '        for item in lst:\n',
    '            if item % 2 == 0:\n',
    '                tmp_res.append(item)\n',
    '        return tmp_res\n',
    '    else:\n',
    '        for item in lst:\n',
    '            if item % 2 != 0:\n',
    '                tmp_res.append(item)\n',
    '        return tmp_res']},
  {'cell_type': 'code',
   'execution_count': 15,
   'id': '43903323',
   'metadata': {},
   'outputs': [{'data': {'text/plain': ['[1, 3, 5]']},
     'execution_count': 15,
     'metadata': {},
     'output_type': 'execute_result'}],
   'source': ['odd_or_even([1,2,3,4,5])']},
  {'cell_type': 'code',
   'execution_count': 16,
   'id': '4b877abd',
   'metadata': {},
   'outputs': [{'data': {'text/plain': ['[1, 3, 5]']},
     'execution_count': 16,
     'metadata': {},
     'output_type': 'execute_result'}],
   'source': ['odd_or_even([1,2,3,4,5], True)']},
  {'cell_type': 'code',
   'execution_count': 18,
   'id': '01d3a9fa',
   'metadata': {},
   'outputs': [{'data': {'text/plain': ['[1, 3, 5]']},
     'execution_count': 18,
     'metadata': {},
     'output_type': 'execute_result'}],
   'source': ['odd_or_even([1,2,3,4,5], odd = True)']},
  {'cell_type': 'code',
   'execution_count': 17,
   'id': '4edd6f63',
   'metadata': {},
   'outputs': [{'data': {'text/plain': ['[2, 4]']},
     'execution_count': 17,
     'metadata': {},
     'output_type': 'execute_result'}],
   'source': ['odd_or_even([1,2,3,4,5], False)']},
  {'cell_type': 'markdown',
   'id': '83a5ad93',
   'metadata': {},
   'source': ['### args, kwargs']},
  {'cell_type': 'code',
   'execution_count': 23,
   'id': '62b29ac2',
   'metadata': {},
   'outputs': [],
   'source': ['def len_of_each_element(*args):\n',
    '    tmp_res = []\n',
    '    for item in args:\n',
    '        #print(item)\n',
    '        tmp_res.append(len(item))\n',
    '    return tmp_res']},
  {'cell_type': 'code',
   'execution_count': 24,
   'id': 'f54eb7e2',
   'metadata': {},
   'outputs': [{'data': {'text/plain': ['[6, 6, 7, 6, 7]']},
     'execution_count': 24,
     'metadata': {},
     'output_type': 'execute_result'}],
   'source': ["len_of_each_element('Привет', 'группа', 'давайте', 'решать', 'задачки')"]},
  {'cell_type': 'code',
   'execution_count': 25,
   'id': '79479479',
   'metadata': {},
   'outputs': [{'data': {'text/plain': ['[6, 6, 7, 6, 7]']},
     'execution_count': 25,
     'metadata': {},
     'output_type': 'execute_result'}],
   'source': ["[len(item) for item in 'Привет группа давайте решать задачки'.split(' ')]"]},
  {'cell_type': 'code',
   'execution_count': 26,
   'id': '0c37fce8',
   'metadata': {},
   'outputs': [{'name': 'stdout',
     'output_type': 'stream',
     'text': ['1\n', '2\n', '3\n', '4\n', '5\n']}],
   'source': ['def lst_len(qq):\n',
    '    for i in qq:\n',
    '        print(i)\n',
    '        \n',
    '\n',
    'lst_len([1,2,3,4,5])']},
  {'cell_type': 'markdown',
   'id': '4ec85930',
   'metadata': {},
   'source': ['### Рекурсия']},
  {'cell_type': 'markdown',
   'id': '3b9a69ef',
   'metadata': {},
   'source': ['### Pythontutor - https://pythontutor.com/visualize.html#code=def%20factorial%28n%29%3A%0A%20%20%20%20if%20n%20%3D%3D%200%3A%0A%20%20%20%20%20%20%20%20return%201%0A%20%20%20%20else%3A%0A%20%20%20%20%20%20%20%20print%28n%29%0A%20%20%20%20%20%20%20%20return%20n%20*%20factorial%28n%20-%201%29%0A%20%20%20%20%20%20%20%20%0Afactorial%285%29&cumulative=false&curInstr=31&heapPrimitives=nevernest&mode=display&origin=opt-frontend.js&py=3&rawInputLstJSON=%5B%5D&textReferences=false']},
  {'cell_type': 'code',
   'execution_count': None,
   'id': 'e149c852',
   'metadata': {},
   'outputs': [],
   'source': ['def factorial(n):\n',
    '    if n == 0:\n',
    '        return 1\n',
    '    else:\n',
    '        print(n)\n',
    '        return n * factorial(n - 1)']},
  {'cell_type': 'code',
   'execution_count': 7,
   'id': '996cb0ff',
   'metadata': {},
   'outputs': [{'name': 'stdout',
     'output_type': 'stream',
     'text': ['5\n',
      '4\n',
      '3\n',
      '2\n',
      '1\n',
      'CPU times: user 81 µs, sys: 38 µs, total: 119 µs\n',
      'Wall time: 91.1 µs\n']},
    {'data': {'text/plain': ['120']},
     'execution_count': 7,
     'metadata': {},
     'output_type': 'execute_result'}],
   'source': ['%%time\n', '\n', 'factorial(5)']},
  {'cell_type': 'code',
   'execution_count': 6,
   'id': 'd6126c6c',
   'metadata': {},
   'outputs': [{'name': 'stdout',
     'output_type': 'stream',
     'text': ['50\n',
      '49\n',
      '48\n',
      '47\n',
      '46\n',
      '45\n',
      '44\n',
      '43\n',
      '42\n',
      '41\n',
      '40\n',
      '39\n',
      '38\n',
      '37\n',
      '36\n',
      '35\n',
      '34\n',
      '33\n',
      '32\n',
      '31\n',
      '30\n',
      '29\n',
      '28\n',
      '27\n',
      '26\n',
      '25\n',
      '24\n',
      '23\n',
      '22\n',
      '21\n',
      '20\n',
      '19\n',
      '18\n',
      '17\n',
      '16\n',
      '15\n',
      '14\n',
      '13\n',
      '12\n',
      '11\n',
      '10\n',
      '9\n',
      '8\n',
      '7\n',
      '6\n',
      '5\n',
      '4\n',
      '3\n',
      '2\n',
      '1\n',
      'CPU times: user 1.1 ms, sys: 1 ms, total: 2.1 ms\n',
      'Wall time: 1.24 ms\n']},
    {'data': {'text/plain': ['30414093201713378043612608166064768844377641568960512000000000000']},
     'execution_count': 6,
     'metadata': {},
     'output_type': 'execute_result'}],
   'source': ['%%time\n', '\n', 'factorial(50)']},
  {'cell_type': 'markdown',
   'id': 'c3bc4637',
   'metadata': {},
   'source': ['### Задачки!']},
  {'cell_type': 'markdown',
   'id': '94167b74',
   'metadata': {},
   'source': ['#### 1. Напишите функцию, которая на вход получает список чисел, а на выход возвращает список из 2 чисел - суммы четных и нечетных. Мы также хотим знать размер первоначального списка, но его в return подавать не надо']},
  {'cell_type': 'code',
   'execution_count': 28,
   'id': 'a4bf2665',
   'metadata': {},
   'outputs': [{'name': 'stdout',
     'output_type': 'stream',
     'text': ['6 3 3\n', '(6, 6) 3\n']}],
   'source': ['def sum_2(li):\n',
    '    odd = 0\n',
    '    even = 0\n',
    '    global j\n',
    '    j = 0\n',
    '    for i in li:\n',
    '        i = int(i)\n',
    '        j += 1\n',
    '        if i % 2 == 0:\n',
    '            even += i\n',
    '        else:\n',
    '            odd += i\n',
    '    return(even, odd)\n',
    '\n',
    'li = input().split()\n',
    'print(sum_2(li), j)']},
  {'cell_type': 'code',
   'execution_count': 29,
   'id': 'e99ff31f',
   'metadata': {},
   'outputs': [],
   'source': ['def foo(l):\n',
    '    global list_len\n',
    '    list_len = len(l)\n',
    '    n = list()\n',
    '    a = 0\n',
    '    b = 0\n',
    '    for i in l:\n',
    '        if i % 2 != 0:\n',
    '            a += i\n',
    '        else:\n',
    '            b += i\n',
    '    n.append(b)\n',
    '    n.append(a)\n',
    '    return (n)']},
  {'cell_type': 'code',
   'execution_count': 30,
   'id': 'b9cad67d',
   'metadata': {},
   'outputs': [{'name': 'stdout', 'output_type': 'stream', 'text': ['6\n']},
    {'data': {'text/plain': ['[12, 9]']},
     'execution_count': 30,
     'metadata': {},
     'output_type': 'execute_result'}],
   'source': ['foo([1,2,3,4,5,6])']},
  {'cell_type': 'markdown',
   'id': '1f5f8dba',
   'metadata': {},
   'source': ['#### 2. На ввод подается список чисел. Вам надо написать одну функцию, которая для каждого числа из списка посчитает: Если число четное - его квадрат, если нечетное - его куб. Внутри функции проверять на четность нельзя']},
  {'cell_type': 'code',
   'execution_count': None,
   'id': 'fb35cf6d',
   'metadata': {},
   'outputs': [],
   'source': ['def fun2_3(i, flag):\n',
    '    if flag:\n',
    '        return(i * i)\n',
    '    else:\n',
    '        return(i ** 3)\n',
    '\n',
    'li = input().split()\n',
    'for i in li:\n',
    '    flagg = False\n',
    '    i = int(i)\n',
    '    if i % 2 == 0:\n',
    '        flagg = True\n',
    '    print(fun2_3(i, flagg))']},
  {'cell_type': 'code',
   'execution_count': None,
   'id': '0fccb781',
   'metadata': {},
   'outputs': [],
   'source': ['def foo(*args):\n',
    '    out = []\n',
    '    for num in args:\n',
    '        out.append(num ** (num % 2 + 2))\n',
    '    return(out)\n',
    '\n',
    'print(foo(1, 2, 3, 4))']},
  {'cell_type': 'code',
   'execution_count': None,
   'id': '7051d23f',
   'metadata': {},
   'outputs': [],
   'source': []},
  {'cell_type': 'code',
   'execution_count': None,
   'id': '929ada8c',
   'metadata': {},
   'outputs': [],
   'source': []}],
 'metadata': {'kernelspec': {'display_name': 'Python 3',
   'language': 'python',
   'name': 'python3'},
  'language_info': {'codemirror_mode': {'name': 'ipython', 'version': 3},
   'file_extension': '.py',
   'mimetype': 'text/x-python',
   'name': 'python',
   'nbconvert_exporter': 'python',
   'pygments_lexer': 'ipython3',
   'version': '3.8.8'}},
 'nbformat': 4,
 'nbformat_minor': 5}

In [12]:
from pprint import pprint
pprint(workbook)

{'cells': [{'cell_type': 'markdown',
            'id': 'c4111e3a',
            'metadata': {},
            'source': ['## Функции - продолжение']},
           {'cell_type': 'markdown',
            'id': '0c506a67',
            'metadata': {},
            'source': ['### Локальные и глобальные переменные']},
           {'cell_type': 'code',
            'execution_count': 10,
            'id': 'f820cf38',
            'metadata': {},
            'outputs': [{'name': 'stdout',
                         'output_type': 'stream',
                         'text': ['Петр\n', 'Вася\n']}],
            'source': ["name = 'Вася'\n",
                       '\n',
                       'def foo():\n',
                       "    name = 'Петр'\n",
                       '    print(name)\n',
                       ' \n',
                       'foo()\n',
                       'print(name)']},
           {'cell_type': 'code',
            'execution_count': 13,
            'id': '42757cdf',
            'metadata': {},
            'outputs': [{'name': 'stdout',
                         'output_type': 'stream',
                         'text': ['Петр\n', 'Петр\n']}],
            'source': ["name = 'Вася'\n",
                       '\n',
                       'def foo():\n',
                       '    global name\n',
                       "    name = 'Петр'\n",
                       '    print(name)\n',
                       ' \n',
                       'foo()\n',
                       'print(name)']},
           {'cell_type': 'markdown',
            'id': 'f71ddefc',
            'metadata': {},
            'source': ['Global переназначает видимость переменной с локальной '
                       '(внутри функции) до глобальной видимости']},
           {'cell_type': 'markdown',
            'id': 'aa17f373',
            'metadata': {},
            'source': ['### Значения по умолчанию']},
           {'cell_type': 'code',
            'execution_count': 19,
            'id': 'fa1543f5',
            'metadata': {},
            'outputs': [],
            'source': ['i = 5\n', 'if i > 6:\n', "    print('dada')"]},
           {'cell_type': 'code',
            'execution_count': 20,
            'id': '2e8d19af',
            'metadata': {},
            'outputs': [{'data': {'text/plain': ['False']},
                         'execution_count': 20,
                         'metadata': {},
                         'output_type': 'execute_result'}],
            'source': ['i > 6']},
           {'cell_type': 'code',
            'execution_count': 14,
            'id': '694b0f58',
            'metadata': {},
            'outputs': [],
            'source': ['# Тут можно убрать один return и немного переписать '
                       'код - как?\n',
                       'def odd_or_even(lst, odd = True):\n',
                       '    tmp_res = []\n',
                       '    if odd == False:\n',
                       '        for item in lst:\n',
                       '            if item % 2 == 0:\n',
                       '                tmp_res.append(item)\n',
                       '        return tmp_res\n',
                       '    else:\n',
                       '        for item in lst:\n',
                       '            if item % 2 != 0:\n',
                       '                tmp_res.append(item)\n',
                       '        return tmp_res']},
           {'cell_type': 'code',
            'execution_count': 15,
            'id': '43903323',
            'metadata': {},
            'outputs': [{'data': {'text/plain': ['[1, 3, 5]']},
                         'execution_count': 15,
                         'metadata': {},
                         'output_type': 'execute_result'}],
            'source': ['odd_or_even([1,2,3,4,5])']},
           {'cell_type': 'code',
            'execution_count': 16,
            'id': '4b877abd',
            'metadata': {},
            'outputs': [{'data': {'text/plain': ['[1, 3, 5]']},
                         'execution_count': 16,
                         'metadata': {},
                         'output_type': 'execute_result'}],
            'source': ['odd_or_even([1,2,3,4,5], True)']},
           {'cell_type': 'code',
            'execution_count': 18,
            'id': '01d3a9fa',
            'metadata': {},
            'outputs': [{'data': {'text/plain': ['[1, 3, 5]']},
                         'execution_count': 18,
                         'metadata': {},
                         'output_type': 'execute_result'}],
            'source': ['odd_or_even([1,2,3,4,5], odd = True)']},
           {'cell_type': 'code',
            'execution_count': 17,
            'id': '4edd6f63',
            'metadata': {},
            'outputs': [{'data': {'text/plain': ['[2, 4]']},
                         'execution_count': 17,
                         'metadata': {},
                         'output_type': 'execute_result'}],
            'source': ['odd_or_even([1,2,3,4,5], False)']},
           {'cell_type': 'markdown',
            'id': '83a5ad93',
            'metadata': {},
            'source': ['### args, kwargs']},
           {'cell_type': 'code',
            'execution_count': 23,
            'id': '62b29ac2',
            'metadata': {},
            'outputs': [],
            'source': ['def len_of_each_element(*args):\n',
                       '    tmp_res = []\n',
                       '    for item in args:\n',
                       '        #print(item)\n',
                       '        tmp_res.append(len(item))\n',
                       '    return tmp_res']},
           {'cell_type': 'code',
            'execution_count': 24,
            'id': 'f54eb7e2',
            'metadata': {},
            'outputs': [{'data': {'text/plain': ['[6, 6, 7, 6, 7]']},
                         'execution_count': 24,
                         'metadata': {},
                         'output_type': 'execute_result'}],
            'source': ["len_of_each_element('Привет', 'группа', 'давайте', "
                       "'решать', 'задачки')"]},
           {'cell_type': 'code',
            'execution_count': 25,
            'id': '79479479',
            'metadata': {},
            'outputs': [{'data': {'text/plain': ['[6, 6, 7, 6, 7]']},
                         'execution_count': 25,
                         'metadata': {},
                         'output_type': 'execute_result'}],
            'source': ["[len(item) for item in 'Привет группа давайте решать "
                       "задачки'.split(' ')]"]},
           {'cell_type': 'code',
            'execution_count': 26,
            'id': '0c37fce8',
            'metadata': {},
            'outputs': [{'name': 'stdout',
                         'output_type': 'stream',
                         'text': ['1\n', '2\n', '3\n', '4\n', '5\n']}],
            'source': ['def lst_len(qq):\n',
                       '    for i in qq:\n',
                       '        print(i)\n',
                       '        \n',
                       '\n',
                       'lst_len([1,2,3,4,5])']},
           {'cell_type': 'markdown',
            'id': '4ec85930',
            'metadata': {},
            'source': ['### Рекурсия']},
           {'cell_type': 'markdown',
            'id': '3b9a69ef',
            'metadata': {},
            'source': ['### Pythontutor - '
                       'https://pythontutor.com/visualize.html#code=def%20factorial%28n%29%3A%0A%20%20%20%20if%20n%20%3D%3D%200%3A%0A%20%20%20%20%20%20%20%20return%201%0A%20%20%20%20else%3A%0A%20%20%20%20%20%20%20%20print%28n%29%0A%20%20%20%20%20%20%20%20return%20n%20*%20factorial%28n%20-%201%29%0A%20%20%20%20%20%20%20%20%0Afactorial%285%29&cumulative=false&curInstr=31&heapPrimitives=nevernest&mode=display&origin=opt-frontend.js&py=3&rawInputLstJSON=%5B%5D&textReferences=false']},
           {'cell_type': 'code',
            'execution_count': None,
            'id': 'e149c852',
            'metadata': {},
            'outputs': [],
            'source': ['def factorial(n):\n',
                       '    if n == 0:\n',
                       '        return 1\n',
                       '    else:\n',
                       '        print(n)\n',
                       '        return n * factorial(n - 1)']},
           {'cell_type': 'code',
            'execution_count': 7,
            'id': '996cb0ff',
            'metadata': {},
            'outputs': [{'name': 'stdout',
                         'output_type': 'stream',
                         'text': ['5\n',
                                  '4\n',
                                  '3\n',
                                  '2\n',
                                  '1\n',
                                  'CPU times: user 81 µs, sys: 38 µs, total: '
                                  '119 µs\n',
                                  'Wall time: 91.1 µs\n']},
                        {'data': {'text/plain': ['120']},
                         'execution_count': 7,
                         'metadata': {},
                         'output_type': 'execute_result'}],
            'source': ['%%time\n', '\n', 'factorial(5)']},
           {'cell_type': 'code',
            'execution_count': 6,
            'id': 'd6126c6c',
            'metadata': {},
            'outputs': [{'name': 'stdout',
                         'output_type': 'stream',
                         'text': ['50\n',
                                  '49\n',
                                  '48\n',
                                  '47\n',
                                  '46\n',
                                  '45\n',
                                  '44\n',
                                  '43\n',
                                  '42\n',
                                  '41\n',
                                  '40\n',
                                  '39\n',
                                  '38\n',
                                  '37\n',
                                  '36\n',
                                  '35\n',
                                  '34\n',
                                  '33\n',
                                  '32\n',
                                  '31\n',
                                  '30\n',
                                  '29\n',
                                  '28\n',
                                  '27\n',
                                  '26\n',
                                  '25\n',
                                  '24\n',
                                  '23\n',
                                  '22\n',
                                  '21\n',
                                  '20\n',
                                  '19\n',
                                  '18\n',
                                  '17\n',
                                  '16\n',
                                  '15\n',
                                  '14\n',
                                  '13\n',
                                  '12\n',
                                  '11\n',
                                  '10\n',
                                  '9\n',
                                  '8\n',
                                  '7\n',
                                  '6\n',
                                  '5\n',
                                  '4\n',
                                  '3\n',
                                  '2\n',
                                  '1\n',
                                  'CPU times: user 1.1 ms, sys: 1 ms, total: '
                                  '2.1 ms\n',
                                  'Wall time: 1.24 ms\n']},
                        {'data': {'text/plain': ['30414093201713378043612608166064768844377641568960512000000000000']},
                         'execution_count': 6,
                         'metadata': {},
                         'output_type': 'execute_result'}],
            'source': ['%%time\n', '\n', 'factorial(50)']},
           {'cell_type': 'markdown',
            'id': 'c3bc4637',
            'metadata': {},
            'source': ['### Задачки!']},
           {'cell_type': 'markdown',
            'id': '94167b74',
            'metadata': {},
            'source': ['#### 1. Напишите функцию, которая на вход получает '
                       'список чисел, а на выход возвращает список из 2 чисел '
                       '- суммы четных и нечетных. Мы также хотим знать размер '
                       'первоначального списка, но его в return подавать не '
                       'надо']},
           {'cell_type': 'code',
            'execution_count': 28,
            'id': 'a4bf2665',
            'metadata': {},
            'outputs': [{'name': 'stdout',
                         'output_type': 'stream',
                         'text': ['6 3 3\n', '(6, 6) 3\n']}],
            'source': ['def sum_2(li):\n',
                       '    odd = 0\n',
                       '    even = 0\n',
                       '    global j\n',
                       '    j = 0\n',
                       '    for i in li:\n',
                       '        i = int(i)\n',
                       '        j += 1\n',
                       '        if i % 2 == 0:\n',
                       '            even += i\n',
                       '        else:\n',
                       '            odd += i\n',
                       '    return(even, odd)\n',
                       '\n',
                       'li = input().split()\n',
                       'print(sum_2(li), j)']},
           {'cell_type': 'code',
            'execution_count': 29,
            'id': 'e99ff31f',
            'metadata': {},
            'outputs': [],
            'source': ['def foo(l):\n',
                       '    global list_len\n',
                       '    list_len = len(l)\n',
                       '    n = list()\n',
                       '    a = 0\n',
                       '    b = 0\n',
                       '    for i in l:\n',
                       '        if i % 2 != 0:\n',
                       '            a += i\n',
                       '        else:\n',
                       '            b += i\n',
                       '    n.append(b)\n',
                       '    n.append(a)\n',
                       '    return (n)']},
           {'cell_type': 'code',
            'execution_count': 30,
            'id': 'b9cad67d',
            'metadata': {},
            'outputs': [{'name': 'stdout',
                         'output_type': 'stream',
                         'text': ['6\n']},
                        {'data': {'text/plain': ['[12, 9]']},
                         'execution_count': 30,
                         'metadata': {},
                         'output_type': 'execute_result'}],
            'source': ['foo([1,2,3,4,5,6])']},
           {'cell_type': 'markdown',
            'id': '1f5f8dba',
            'metadata': {},
            'source': ['#### 2. На ввод подается список чисел. Вам надо '
                       'написать одну функцию, которая для каждого числа из '
                       'списка посчитает: Если число четное - его квадрат, '
                       'если нечетное - его куб. Внутри функции проверять на '
                       'четность нельзя']},
           {'cell_type': 'code',
            'execution_count': None,
            'id': 'fb35cf6d',
            'metadata': {},
            'outputs': [],
            'source': ['def fun2_3(i, flag):\n',
                       '    if flag:\n',
                       '        return(i * i)\n',
                       '    else:\n',
                       '        return(i ** 3)\n',
                       '\n',
                       'li = input().split()\n',
                       'for i in li:\n',
                       '    flagg = False\n',
                       '    i = int(i)\n',
                       '    if i % 2 == 0:\n',
                       '        flagg = True\n',
                       '    print(fun2_3(i, flagg))']},
           {'cell_type': 'code',
            'execution_count': None,
            'id': '0fccb781',
            'metadata': {},
            'outputs': [],
            'source': ['def foo(*args):\n',
                       '    out = []\n',
                       '    for num in args:\n',
                       '        out.append(num ** (num % 2 + 2))\n',
                       '    return(out)\n',
                       '\n',
                       'print(foo(1, 2, 3, 4))']},
           {'cell_type': 'code',
            'execution_count': None,
            'id': '7051d23f',
            'metadata': {},
            'outputs': [],
            'source': []},
           {'cell_type': 'code',
            'execution_count': None,
            'id': '929ada8c',
            'metadata': {},
            'outputs': [],
            'source': []}],
 'metadata': {'kernelspec': {'display_name': 'Python 3',
                             'language': 'python',
                             'name': 'python3'},
              'language_info': {'codemirror_mode': {'name': 'ipython',
                                                    'version': 3},
                                'file_extension': '.py',
                                'mimetype': 'text/x-python',
                                'name': 'python',
                                'nbconvert_exporter': 'python',
                                'pygments_lexer': 'ipython3',
                                'version': '3.8.8'}},
 'nbformat': 4,
 'nbformat_minor': 5}

In [16]:
print(json.dumps(workbook, indent = 4))

{
    "cells": [
        {
            "cell_type": "markdown",
            "id": "c4111e3a",
            "metadata": {},
            "source": [
                "## \u0424\u0443\u043d\u043a\u0446\u0438\u0438 - \u043f\u0440\u043e\u0434\u043e\u043b\u0436\u0435\u043d\u0438\u0435"
            ]
        },
        {
            "cell_type": "markdown",
            "id": "0c506a67",
            "metadata": {},
            "source": [
                "### \u041b\u043e\u043a\u0430\u043b\u044c\u043d\u044b\u0435 \u0438 \u0433\u043b\u043e\u0431\u0430\u043b\u044c\u043d\u044b\u0435 \u043f\u0435\u0440\u0435\u043c\u0435\u043d\u043d\u044b\u0435"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": 10,
            "id": "f820cf38",
            "metadata": {},
            "outputs": [
                {
                    "name": "stdout",
                    "output_type": "stream",
                    "text": [
                        "\u041f\u0435\u0442\u0440\n",
                        "\u0412\u0430\u0441\u044f\n"
                    ]
                }
            ],
            "source": [
                "name = '\u0412\u0430\u0441\u044f'\n",
                "\n",
                "def foo():\n",
                "    name = '\u041f\u0435\u0442\u0440'\n",
                "    print(name)\n",
                " \n",
                "foo()\n",
                "print(name)"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": 13,
            "id": "42757cdf",
            "metadata": {},
            "outputs": [
                {
                    "name": "stdout",
                    "output_type": "stream",
                    "text": [
                        "\u041f\u0435\u0442\u0440\n",
                        "\u041f\u0435\u0442\u0440\n"
                    ]
                }
            ],
            "source": [
                "name = '\u0412\u0430\u0441\u044f'\n",
                "\n",
                "def foo():\n",
                "    global name\n",
                "    name = '\u041f\u0435\u0442\u0440'\n",
                "    print(name)\n",
                " \n",
                "foo()\n",
                "print(name)"
            ]
        },
        {
            "cell_type": "markdown",
            "id": "f71ddefc",
            "metadata": {},
            "source": [
                "Global \u043f\u0435\u0440\u0435\u043d\u0430\u0437\u043d\u0430\u0447\u0430\u0435\u0442 \u0432\u0438\u0434\u0438\u043c\u043e\u0441\u0442\u044c \u043f\u0435\u0440\u0435\u043c\u0435\u043d\u043d\u043e\u0439 \u0441 \u043b\u043e\u043a\u0430\u043b\u044c\u043d\u043e\u0439 (\u0432\u043d\u0443\u0442\u0440\u0438 \u0444\u0443\u043d\u043a\u0446\u0438\u0438) \u0434\u043e \u0433\u043b\u043e\u0431\u0430\u043b\u044c\u043d\u043e\u0439 \u0432\u0438\u0434\u0438\u043c\u043e\u0441\u0442\u0438"
            ]
        },
        {
            "cell_type": "markdown",
            "id": "aa17f373",
            "metadata": {},
            "source": [
                "### \u0417\u043d\u0430\u0447\u0435\u043d\u0438\u044f \u043f\u043e \u0443\u043c\u043e\u043b\u0447\u0430\u043d\u0438\u044e"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": 19,
            "id": "fa1543f5",
            "metadata": {},
            "outputs": [],
            "source": [
                "i = 5\n",
                "if i > 6:\n",
                "    print('dada')"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": 20,
            "id": "2e8d19af",
            "metadata": {},
            "outputs": [
                {
                    "data": {
                        "text/plain": [
                            "False"
                        ]
                    },
                    "execution_count": 20,
                    "metadata": {},
                    "output_type": "execute_result"
                }
            ],
            "source": [
                "i > 6"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": 14,
            "id": "694b0f58",
            "metadata": {},
            "outputs": [],
            "source": [
                "# \u0422\u0443\u0442 \u043c\u043e\u0436\u043d\u043e \u0443\u0431\u0440\u0430\u0442\u044c \u043e\u0434\u0438\u043d return \u0438 \u043d\u0435\u043c\u043d\u043e\u0433\u043e \u043f\u0435\u0440\u0435\u043f\u0438\u0441\u0430\u0442\u044c \u043a\u043e\u0434 - \u043a\u0430\u043a?\n",
                "def odd_or_even(lst, odd = True):\n",
                "    tmp_res = []\n",
                "    if odd == False:\n",
                "        for item in lst:\n",
                "            if item % 2 == 0:\n",
                "                tmp_res.append(item)\n",
                "        return tmp_res\n",
                "    else:\n",
                "        for item in lst:\n",
                "            if item % 2 != 0:\n",
                "                tmp_res.append(item)\n",
                "        return tmp_res"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": 15,
            "id": "43903323",
            "metadata": {},
            "outputs": [
                {
                    "data": {
                        "text/plain": [
                            "[1, 3, 5]"
                        ]
                    },
                    "execution_count": 15,
                    "metadata": {},
                    "output_type": "execute_result"
                }
            ],
            "source": [
                "odd_or_even([1,2,3,4,5])"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": 16,
            "id": "4b877abd",
            "metadata": {},
            "outputs": [
                {
                    "data": {
                        "text/plain": [
                            "[1, 3, 5]"
                        ]
                    },
                    "execution_count": 16,
                    "metadata": {},
                    "output_type": "execute_result"
                }
            ],
            "source": [
                "odd_or_even([1,2,3,4,5], True)"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": 18,
            "id": "01d3a9fa",
            "metadata": {},
            "outputs": [
                {
                    "data": {
                        "text/plain": [
                            "[1, 3, 5]"
                        ]
                    },
                    "execution_count": 18,
                    "metadata": {},
                    "output_type": "execute_result"
                }
            ],
            "source": [
                "odd_or_even([1,2,3,4,5], odd = True)"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": 17,
            "id": "4edd6f63",
            "metadata": {},
            "outputs": [
                {
                    "data": {
                        "text/plain": [
                            "[2, 4]"
                        ]
                    },
                    "execution_count": 17,
                    "metadata": {},
                    "output_type": "execute_result"
                }
            ],
            "source": [
                "odd_or_even([1,2,3,4,5], False)"
            ]
        },
        {
            "cell_type": "markdown",
            "id": "83a5ad93",
            "metadata": {},
            "source": [
                "### args, kwargs"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": 23,
            "id": "62b29ac2",
            "metadata": {},
            "outputs": [],
            "source": [
                "def len_of_each_element(*args):\n",
                "    tmp_res = []\n",
                "    for item in args:\n",
                "        #print(item)\n",
                "        tmp_res.append(len(item))\n",
                "    return tmp_res"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": 24,
            "id": "f54eb7e2",
            "metadata": {},
            "outputs": [
                {
                    "data": {
                        "text/plain": [
                            "[6, 6, 7, 6, 7]"
                        ]
                    },
                    "execution_count": 24,
                    "metadata": {},
                    "output_type": "execute_result"
                }
            ],
            "source": [
                "len_of_each_element('\u041f\u0440\u0438\u0432\u0435\u0442', '\u0433\u0440\u0443\u043f\u043f\u0430', '\u0434\u0430\u0432\u0430\u0439\u0442\u0435', '\u0440\u0435\u0448\u0430\u0442\u044c', '\u0437\u0430\u0434\u0430\u0447\u043a\u0438')"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": 25,
            "id": "79479479",
            "metadata": {},
            "outputs": [
                {
                    "data": {
                        "text/plain": [
                            "[6, 6, 7, 6, 7]"
                        ]
                    },
                    "execution_count": 25,
                    "metadata": {},
                    "output_type": "execute_result"
                }
            ],
            "source": [
                "[len(item) for item in '\u041f\u0440\u0438\u0432\u0435\u0442 \u0433\u0440\u0443\u043f\u043f\u0430 \u0434\u0430\u0432\u0430\u0439\u0442\u0435 \u0440\u0435\u0448\u0430\u0442\u044c \u0437\u0430\u0434\u0430\u0447\u043a\u0438'.split(' ')]"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": 26,
            "id": "0c37fce8",
            "metadata": {},
            "outputs": [
                {
                    "name": "stdout",
                    "output_type": "stream",
                    "text": [
                        "1\n",
                        "2\n",
                        "3\n",
                        "4\n",
                        "5\n"
                    ]
                }
            ],
            "source": [
                "def lst_len(qq):\n",
                "    for i in qq:\n",
                "        print(i)\n",
                "        \n",
                "\n",
                "lst_len([1,2,3,4,5])"
            ]
        },
        {
            "cell_type": "markdown",
            "id": "4ec85930",
            "metadata": {},
            "source": [
                "### \u0420\u0435\u043a\u0443\u0440\u0441\u0438\u044f"
            ]
        },
        {
            "cell_type": "markdown",
            "id": "3b9a69ef",
            "metadata": {},
            "source": [
                "### Pythontutor - https://pythontutor.com/visualize.html#code=def%20factorial%28n%29%3A%0A%20%20%20%20if%20n%20%3D%3D%200%3A%0A%20%20%20%20%20%20%20%20return%201%0A%20%20%20%20else%3A%0A%20%20%20%20%20%20%20%20print%28n%29%0A%20%20%20%20%20%20%20%20return%20n%20*%20factorial%28n%20-%201%29%0A%20%20%20%20%20%20%20%20%0Afactorial%285%29&cumulative=false&curInstr=31&heapPrimitives=nevernest&mode=display&origin=opt-frontend.js&py=3&rawInputLstJSON=%5B%5D&textReferences=false"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": null,
            "id": "e149c852",
            "metadata": {},
            "outputs": [],
            "source": [
                "def factorial(n):\n",
                "    if n == 0:\n",
                "        return 1\n",
                "    else:\n",
                "        print(n)\n",
                "        return n * factorial(n - 1)"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": 7,
            "id": "996cb0ff",
            "metadata": {},
            "outputs": [
                {
                    "name": "stdout",
                    "output_type": "stream",
                    "text": [
                        "5\n",
                        "4\n",
                        "3\n",
                        "2\n",
                        "1\n",
                        "CPU times: user 81 \u00b5s, sys: 38 \u00b5s, total: 119 \u00b5s\n",
                        "Wall time: 91.1 \u00b5s\n"
                    ]
                },
                {
                    "data": {
                        "text/plain": [
                            "120"
                        ]
                    },
                    "execution_count": 7,
                    "metadata": {},
                    "output_type": "execute_result"
                }
            ],
            "source": [
                "%%time\n",
                "\n",
                "factorial(5)"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": 6,
            "id": "d6126c6c",
            "metadata": {},
            "outputs": [
                {
                    "name": "stdout",
                    "output_type": "stream",
                    "text": [
                        "50\n",
                        "49\n",
                        "48\n",
                        "47\n",
                        "46\n",
                        "45\n",
                        "44\n",
                        "43\n",
                        "42\n",
                        "41\n",
                        "40\n",
                        "39\n",
                        "38\n",
                        "37\n",
                        "36\n",
                        "35\n",
                        "34\n",
                        "33\n",
                        "32\n",
                        "31\n",
                        "30\n",
                        "29\n",
                        "28\n",
                        "27\n",
                        "26\n",
                        "25\n",
                        "24\n",
                        "23\n",
                        "22\n",
                        "21\n",
                        "20\n",
                        "19\n",
                        "18\n",
                        "17\n",
                        "16\n",
                        "15\n",
                        "14\n",
                        "13\n",
                        "12\n",
                        "11\n",
                        "10\n",
                        "9\n",
                        "8\n",
                        "7\n",
                        "6\n",
                        "5\n",
                        "4\n",
                        "3\n",
                        "2\n",
                        "1\n",
                        "CPU times: user 1.1 ms, sys: 1 ms, total: 2.1 ms\n",
                        "Wall time: 1.24 ms\n"
                    ]
                },
                {
                    "data": {
                        "text/plain": [
                            "30414093201713378043612608166064768844377641568960512000000000000"
                        ]
                    },
                    "execution_count": 6,
                    "metadata": {},
                    "output_type": "execute_result"
                }
            ],
            "source": [
                "%%time\n",
                "\n",
                "factorial(50)"
            ]
        },
        {
            "cell_type": "markdown",
            "id": "c3bc4637",
            "metadata": {},
            "source": [
                "### \u0417\u0430\u0434\u0430\u0447\u043a\u0438!"
            ]
        },
        {
            "cell_type": "markdown",
            "id": "94167b74",
            "metadata": {},
            "source": [
                "#### 1. \u041d\u0430\u043f\u0438\u0448\u0438\u0442\u0435 \u0444\u0443\u043d\u043a\u0446\u0438\u044e, \u043a\u043e\u0442\u043e\u0440\u0430\u044f \u043d\u0430 \u0432\u0445\u043e\u0434 \u043f\u043e\u043b\u0443\u0447\u0430\u0435\u0442 \u0441\u043f\u0438\u0441\u043e\u043a \u0447\u0438\u0441\u0435\u043b, \u0430 \u043d\u0430 \u0432\u044b\u0445\u043e\u0434 \u0432\u043e\u0437\u0432\u0440\u0430\u0449\u0430\u0435\u0442 \u0441\u043f\u0438\u0441\u043e\u043a \u0438\u0437 2 \u0447\u0438\u0441\u0435\u043b - \u0441\u0443\u043c\u043c\u044b \u0447\u0435\u0442\u043d\u044b\u0445 \u0438 \u043d\u0435\u0447\u0435\u0442\u043d\u044b\u0445. \u041c\u044b \u0442\u0430\u043a\u0436\u0435 \u0445\u043e\u0442\u0438\u043c \u0437\u043d\u0430\u0442\u044c \u0440\u0430\u0437\u043c\u0435\u0440 \u043f\u0435\u0440\u0432\u043e\u043d\u0430\u0447\u0430\u043b\u044c\u043d\u043e\u0433\u043e \u0441\u043f\u0438\u0441\u043a\u0430, \u043d\u043e \u0435\u0433\u043e \u0432 return \u043f\u043e\u0434\u0430\u0432\u0430\u0442\u044c \u043d\u0435 \u043d\u0430\u0434\u043e"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": 28,
            "id": "a4bf2665",
            "metadata": {},
            "outputs": [
                {
                    "name": "stdout",
                    "output_type": "stream",
                    "text": [
                        "6 3 3\n",
                        "(6, 6) 3\n"
                    ]
                }
            ],
            "source": [
                "def sum_2(li):\n",
                "    odd = 0\n",
                "    even = 0\n",
                "    global j\n",
                "    j = 0\n",
                "    for i in li:\n",
                "        i = int(i)\n",
                "        j += 1\n",
                "        if i % 2 == 0:\n",
                "            even += i\n",
                "        else:\n",
                "            odd += i\n",
                "    return(even, odd)\n",
                "\n",
                "li = input().split()\n",
                "print(sum_2(li), j)"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": 29,
            "id": "e99ff31f",
            "metadata": {},
            "outputs": [],
            "source": [
                "def foo(l):\n",
                "    global list_len\n",
                "    list_len = len(l)\n",
                "    n = list()\n",
                "    a = 0\n",
                "    b = 0\n",
                "    for i in l:\n",
                "        if i % 2 != 0:\n",
                "            a += i\n",
                "        else:\n",
                "            b += i\n",
                "    n.append(b)\n",
                "    n.append(a)\n",
                "    return (n)"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": 30,
            "id": "b9cad67d",
            "metadata": {},
            "outputs": [
                {
                    "name": "stdout",
                    "output_type": "stream",
                    "text": [
                        "6\n"
                    ]
                },
                {
                    "data": {
                        "text/plain": [
                            "[12, 9]"
                        ]
                    },
                    "execution_count": 30,
                    "metadata": {},
                    "output_type": "execute_result"
                }
            ],
            "source": [
                "foo([1,2,3,4,5,6])"
            ]
        },
        {
            "cell_type": "markdown",
            "id": "1f5f8dba",
            "metadata": {},
            "source": [

<hr>
<p>Файл - <a href='https://clck.ru/dX8vx'>https://clck.ru/dX8vx</a><p>
<ol>
    <li>Найти топ 10 городов с самой большой разницей температур за timestamp</li>
    <li>Найти названия городов с пробелами и заменить их на нижнее подчеркивание</li>
</ol>

In [40]:
with open('weather_16 (1).json', 'r', encoding = 'utf-8') as file:
    weather_data = json.load(file)
temp_dict = {city['city']['name'] : city['main']['temp_max'] - city['main']['temp_min'] 
 for city in weather_data}

In [56]:
zz[:10]

['Azadshahr',
 'Abqaiq',
 'Baghdad',
 'Khalis',
 'Ad Dujayl',
 'Qarchak',
 'Kūchaklī',
 'Az Zubayr',
 'Al Harithah',
 'Al Basrah']

In [57]:
sorted(temp_dict, key=temp_dict.get)

['Abs',
 'Ad Dann',
 'Ad Dis ash Sharqiyah',
 'Ad Diwaniyah',
 'Ad Durayhimi',
 'Ajdabiya',
 'Al Abr',
 'Al Amarah',
 'Al Anan',
 'Al Aqir',
 'Al Aziziyah',
 'Al Bayda',
 'Al Faw',
 'Al Ghaylah',
 'Al Ghayzah',
 'Al Hajab',
 'Al Harf',
 'Al Hayy',
 'Al Hazm',
 'Al Hindiyah',
 'Al Hudaydah',
 'Al Jabin',
 'Al Jarrahi',
 'Al Jawf',
 'Al Jawl',
 'Al Khasamah',
 'Al Kut',
 'Al Luhayyah',
 'Al Maalla',
 'Al Majar al Kabir',
 'Al Makdash',
 'Al Malahit',
 'Al Marawiah',
 'Al Maudah',
 'Al Mawsil al Jadidah',
 'Al Mighlaf',
 'Al Milah',
 'Al Mishkhab',
 'Al Misrakh',
 'Al Munirah',
 'Al Musayyib',
 'Al Qaflah',
 'Al Qaryah',
 'Al Tuhayta',
 'Al Udayn',
 'Al Ḩabīt',
 'Al Ḩamzāt',
 'Al ‘Urūbah',
 'Ali al Gharbi',
 'Amd',
 'An Nadirah',
 'An Najaf al Ashraf',
 'An Nasiriyah',
 'Anat al Qadimah',
 'Ar Ramadi',
 'Ar Rawdah',
 'Ar Rawnah',
 'Ar Rutbah',
 'Ariqah',
 'As Safaqayn',
 'As Salasil',
 'As Salif',
 'As Samawah',
 'As Sawarah as Sughra',
 'As Sulaymaniyah',
 'As Suwayda',
 'Asdas',
 'Ash Shaghadirah',
 'Ash Shahil',
 'Ash Sharyah',
 'Ash Shatrah',
 'Ash Shatt',
 'Ash Shaykh Uthman',
 'Ash Shihr',
 'At Taj',
 'At Turbah',
 'Ataq',
 'Az Zahir',
 'Az Zuwaytinah',
 'Bajil',
 'Balad',
 'Bani Bakr',
 'Bani Hujjaj',
 'Baydhabo',
 'Bayhan',
 'Bayji',
 'Bayt al Faqih',
 'Behelidle',
 'Behjatābād',
 'Beledweyne',
 'Bereeda',
 'Bidbadah',
 'Buraydah',
 'Cadale',
 'Cadayo',
 'Ceek',
 'Ceeldheer',
 'Ceerigaabo',
 'Chamchamal',
 'Cheli Gu',
 'Dahasuways',
 'Dalooldho',
 'Dar an Nasr',
 'Darnah',
 'Dawran',
 'Dawran ad Daydah',
 'Dhamar',
 'Dhaybin',
 'Dhi Naim',
 'Dhi as Sufal',
 'Doon',
 'Dīgāleh',
 'El Ad',
 'El Dubat',
 'Eyl',
 'Gialo',
 'Gobolka Galguduud',
 'Gobolka Hiiraan',
 'Gobolka Jubbada Dhexe',
 'Gobolka Mudug',
 'Gobolka Nugaal',
 'Gobolka Woqooyi Galbeed',
 'Hadithah',
 'Hajjah',
 'Halabjah',
 'Harad',
 'Haswayn',
 'Hawf',
 'Hayfan',
 'Hays',
 'Hit',
 'Hobyo',
 'Huraydah',
 'Huth',
 'Ibb',
 'Istgah-e Garmsar',
 'Jaar',
 'Jawf al Maqbabah',
 'Jawhar',
 'Jiblah',
 'Jihanah',
 'Jilib',
 'Juban',
 'Judaydah',
 'Kahriz',
 'Kalāteh-ye Dowlat',
 'Kamb al ‘Ajjāj',
 'Karbala',
 'Khamir',
 'Khawr Maksar',
 'Khorram Darreh',
 'Kilmia',
 'Kirsh',
 'Kismaayo',
 'Kitaf',
 'Koysinceq',
 'Kuaydinah',
 'Kuhlan Afar',
 'Laasqoray',
 'Lawdar',
 "Ma'rib",
 'Mabar',
 'Madinat Labus',
 'Madīnat Dhamār',
 'Mafhaq',
 'Mahaddayweyne',
 'Majzar',
 'Manakhah',
 'Manwakh',
 'Marib City',
 'Matwah',
 'Mawiyah',
 'Mawza',
 'Milah',
 'Mogadishu',
 'Mustaba',
 'Muḩāfaz̧at Dhamār',
 'Muḩāfaz̧at Shabwah',
 'Muḩāfaz̧at al Jawf',
 'Muḩāfaz̧at Şa‘dah',
 'Māmā’ī',
 'Nahiyat Ghammas',
 'Nahiyat Saddat al Hindiyah',
 'Najd al Jumai',
 'Najran',
 'Nurabad',
 'Oodweyne',
 'Paynjuwayn',
 'Protaras',
 'Qabāghlū',
 'Qada Talkif',
 'Qada al Hamdaniyah',
 'Qalat Bishah',
 'Qaloocan',
 'Qishn',
 'Rabigh',
 'Ravīndūzaq',
 'Rawanduz',
 'Republic of Rwanda',
 'Rudum',
 'Sah',
 'Sahar',
 'Said',
 'Sana',
 'Shahrīār Kandeh',
 'Shibam',
 'Shihan as Sufla',
 'Sif',
 'Somalia',
 'Sultanah',
 'Suq ar Rabu',
 'Tabuk',
 'Taglag',
 'Tamrida',
 'Ta‘izz',
 'Tobruk',
 'Tozkhurmato',
 'Turayf',
 'Umm Lajj',
 'Usaylan',
 'Waajid',
 'Wadarah',
 'Yanbu al Bahr',
 'Yarīm',
 'Zarajah',
 'Zbe',
 'Zīrjān',
 'Ţālesh Maḩalleh',
 'Ḩajjah',
 'Ḩeşār-e Sefīd']

In [46]:
zz = sorted(temp_dict, key=temp_dict.get)
for item in zz:
    print(item, temp_dict[item])

Azadshahr 5.0
Abqaiq 4.0
Baghdad 3.0
Khalis 3.0
Ad Dujayl 3.0
Qarchak 2.0
Kūchaklī 2.0
Az Zubayr 2.0
Al Harithah 2.0
Al Basrah 2.0
Protaras 1.329999999999984
Kahriz 1.0
Ḩeşār-e Sefīd 1.0
Jilib 0.0
Kismaayo 0.0
Eyl 0.0
Mogadishu 0.0
Ceerigaabo 0.0
Beledweyne 0.0
Baydhabo 0.0
Istgah-e Garmsar 0.0
Ceeldheer 0.0
Jawhar 0.0
Khorram Darreh 0.0
Nurabad 0.0
Gobolka Jubbada Dhexe 0.0
Yarīm 0.0
Hobyo 0.0
As Suwayda 0.0
Ar Rawnah 0.0
Ash Shihr 0.0
Cadale 0.0
Gobolka Hiiraan 0.0
Behjatābād 0.0
Doon 0.0
Abs 0.0
Behelidle 0.0
Majzar 0.0
Cheli Gu 0.0
Mahaddayweyne 0.0
Laasqoray 0.0
Najd al Jumai 0.0
Suq ar Rabu 0.0
Gobolka Galguduud 0.0
Dahasuways 0.0
Sahar 0.0
El Ad 0.0
Gobolka Mudug 0.0
Shahrīār Kandeh 0.0
Muḩāfaz̧at Şa‘dah 0.0
Al Ghaylah 0.0
Al Jabin 0.0
Hajjah 0.0
Somalia 0.0
Ravīndūzaq 0.0
Ceek 0.0
Bidbadah 0.0
Ta‘izz 0.0
Gobolka Woqooyi Galbeed 0.0
Kalāteh-ye Dowlat 0.0
Al Anan 0.0
Cadayo 0.0
As Sawarah as Sughra 0.0
El Dubat 0.0
Republic of Rwanda 0.0
Dhi as Sufal 0.0
Manwakh 0.0
Mawza 0.0
Bereeda 0.0
Bayt al Faqih 0.0
Dīgāleh 0.0
Milah 0.0
Māmā’ī 0.0
Ma'rib 0.0
Az Zahir 0.0
Qishn 0.0
Usaylan 0.0
Al Jawl 0.0
Bajil 0.0
Marib City 0.0
Mawiyah 0.0
Lawdar 0.0
Manakhah 0.0
Zīrjān 0.0
Zarajah 0.0
Sif 0.0
Shihan as Sufla 0.0
Rudum 0.0
Oodweyne 0.0
Matwah 0.0
Judaydah 0.0
Kuhlan Afar 0.0
Ţālesh Maḩalleh 0.0
Mafhaq 0.0
Dalooldho 0.0
Al Malahit 0.0
Qabāghlū 0.0
Ariqah 0.0
Mabar 0.0
Gobolka Nugaal 0.0
Sah 0.0
Qaloocan 0.0
Mustaba 0.0
Taglag 0.0
Waajid 0.0
Wadarah 0.0
Dawran 0.0
Al Maalla 0.0
Al Hudaydah 0.0
Kuaydinah 0.0
Darnah 0.0
Sana 0.0
Shibam 0.0
Muḩāfaz̧at Shabwah 0.0
Khamir 0.0
Madinat Labus 0.0
Az Zuwaytinah 0.0
Jawf al Maqbabah 0.0
At Taj 0.0
Harad 0.0
Juban 0.0
Jihanah 0.0
Tamrida 0.0
Al Bayda 0.0
Kitaf 0.0
Khawr Maksar 0.0
Hawf 0.0
Kilmia 0.0
Ajdabiya 0.0
Haswayn 0.0
Ḩajjah 0.0
Dhi Naim 0.0
Hayfan 0.0
Ash Sharyah 0.0
Tozkhurmato 0.0
Jaar 0.0
Huth 0.0
Qada Talkif 0.0
Dhamar 0.0
Jiblah 0.0
Al Tuhayta 0.0
Dar an Nasr 0.0
Muḩāfaz̧at al Jawf 0.0
Nahiyat Saddat al Hindiyah 0.0
Rawanduz 0.0
Tobruk 0.0
Qada al Hamdaniyah 0.0
Al Abr 0.0
Bani Bakr 0.0
Dhaybin 0.0
Muḩāfaz̧at Dhamār 0.0
Karbala 0.0
As Salasil 0.0
Koysinceq 0.0
Madīnat Dhamār 0.0
Ibb 0.0
Dawran ad Daydah 0.0
Hit 0.0
Al Maudah 0.0
Halabjah 0.0
Bayji 0.0
Said 0.0
Paynjuwayn 0.0
Balad 0.0
Al Misrakh 0.0
Al Munirah 0.0
Bayhan 0.0
Al Udayn 0.0
Hays 0.0
As Salif 0.0
At Turbah 0.0
As Sulaymaniyah 0.0
Al Qaflah 0.0
As Samawah 0.0
Ar Rutbah 0.0
Ash Shatrah 0.0
Ataq 0.0
An Nasiriyah 0.0
Al Hajab 0.0
Ar Ramadi 0.0
An Najaf al Ashraf 0.0
Anat al Qadimah 0.0
Al Qaryah 0.0
Hadithah 0.0
An Nadirah 0.0
Chamchamal 0.0
Bani Hujjaj 0.0
Al Musayyib 0.0
Al Majar al Kabir 0.0
Al Mawsil al Jadidah 0.0
Al Mishkhab 0.0
Al Hazm 0.0
Al Milah 0.0
Al Kut 0.0
Amd 0.0
Al Aziziyah 0.0
Al Makdash 0.0
Ali al Gharbi 0.0
Ash Shaykh Uthman 0.0
Al Khasamah 0.0
Ash Shahil 0.0
Al Aqir 0.0
Al Jawf 0.0
Kamb al ‘Ajjāj 0.0
Al Amarah 0.0
Ad Diwaniyah 0.0
Turayf 0.0
Umm Lajj 0.0
Yanbu al Bahr 0.0
Tabuk 0.0
Sultanah 0.0
Ad Durayhimi 0.0
Al Mighlaf 0.0
Al Marawiah 0.0
Al Ghayzah 0.0
Al Jarrahi 0.0
Al Harf 0.0
Al Ḩabīt 0.0
Ash Shaghadirah 0.0
Al Ḩamzāt 0.0
Al Luhayyah 0.0
Kirsh 0.0
As Safaqayn 0.0
Huraydah 0.0
Ar Rawdah 0.0
Ash Shatt 0.0
Gialo 0.0
Al Hindiyah 0.0
Nahiyat Ghammas 0.0
Al Hayy 0.0
Al Faw 0.0
Al ‘Urūbah 0.0
Ad Dis ash Sharqiyah 0.0
Ad Dann 0.0
Asdas 0.0
Rabigh 0.0
Qalat Bishah 0.0
Najran 0.0
Buraydah 0.0
Zbe 0.0

In [47]:
import json
with open('weather_16 (1).json', 'r', encoding='UTF8') as file:
    city = json.load(file)
    t_city = []
    for line in city:
        temp = float(line['main']['temp_max']) - float(line['main']['temp_min'])
        t_city.append((temp, line['city']['name']))
        if ' ' in line['city']['name']:
            line['city']['name'] = line['city']['name'].replace(' ', '_')
            print(line['city']['name'])
t_city = sorted(t_city, reverse = True)
for i in range(10):
    print(t_city[i])

Istgah-e_Garmsar
Khorram_Darreh
Gobolka_Jubbada_Dhexe
As_Suwayda
Ar_Rawnah
Ash_Shihr
Gobolka_Hiiraan
Cheli_Gu
Najd_al_Jumai
Suq_ar_Rabu
Gobolka_Galguduud
El_Ad
Gobolka_Mudug
Shahrīār_Kandeh
Muḩāfaz̧at_Şa‘dah
Al_Ghaylah
Al_Jabin
Gobolka_Woqooyi_Galbeed
Kalāteh-ye_Dowlat
Al_Anan
As_Sawarah_as_Sughra
El_Dubat
Republic_of_Rwanda
Dhi_as_Sufal
Bayt_al_Faqih
Az_Zahir
Al_Jawl
Marib_City
Shihan_as_Sufla
Kuhlan_Afar
Ţālesh_Maḩalleh
Al_Malahit
Gobolka_Nugaal
Ḩeşār-e_Sefīd
Al_Maalla
Al_Hudaydah
Muḩāfaz̧at_Shabwah
Madinat_Labus
Az_Zuwaytinah
Jawf_al_Maqbabah
At_Taj
Al_Bayda
Khawr_Maksar
Dhi_Naim
Ash_Sharyah
Qada_Talkif
Al_Tuhayta
Dar_an_Nasr
Muḩāfaz̧at_al_Jawf
Nahiyat_Saddat_al_Hindiyah
Qada_al_Hamdaniyah
Al_Abr
Bani_Bakr
Muḩāfaz̧at_Dhamār
As_Salasil
Madīnat_Dhamār
Dawran_ad_Daydah
Al_Maudah
Az_Zubayr
Al_Misrakh
Al_Munirah
Al_Udayn
As_Salif
At_Turbah
As_Sulaymaniyah
Al_Qaflah
As_Samawah
Ar_Rutbah
Ash_Shatrah
An_Nasiriyah
Al_Hajab
Ar_Ramadi
An_Najaf_al_Ashraf
Anat_al_Qadimah
Al_Qaryah
An_Nadirah
Bani_Hujjaj
Al_Musayyib
Al_Majar_al_Kabir
Al_Mawsil_al_Jadidah
Al_Mishkhab
Al_Hazm
Al_Milah
Al_Kut
Al_Aziziyah
Al_Makdash
Ali_al_Gharbi
Ash_Shaykh_Uthman
Al_Khasamah
Ash_Shahil
Al_Aqir
Al_Jawf
Kamb_al_‘Ajjāj
Al_Amarah
Ad_Diwaniyah
Ad_Dujayl
Umm_Lajj
Yanbu_al_Bahr
Ad_Durayhimi
Al_Mighlaf
Al_Marawiah
Al_Ghayzah
Al_Jarrahi
Al_Harf
Al_Ḩabīt
Ash_Shaghadirah
Al_Ḩamzāt
Al_Luhayyah
As_Safaqayn
Ar_Rawdah
Ash_Shatt
Al_Harithah
Al_Basrah
Al_Hindiyah
Nahiyat_Ghammas
Al_Hayy
Al_Faw
Al_‘Urūbah
Ad_Dis_ash_Sharqiyah
Ad_Dann
Qalat_Bishah
(5.0, 'Azadshahr')
(4.0, 'Abqaiq')
(3.0, 'Khalis')
(3.0, 'Baghdad')
(3.0, 'Ad Dujayl')
(2.0, 'Qarchak')
(2.0, 'Kūchaklī')
(2.0, 'Az Zubayr')
(2.0, 'Al Harithah')
(2.0, 'Al Basrah')

In [49]:
t_city[:10]

[(5.0, 'Azadshahr'),
 (4.0, 'Abqaiq'),
 (3.0, 'Khalis'),
 (3.0, 'Baghdad'),
 (3.0, 'Ad Dujayl'),
 (2.0, 'Qarchak'),
 (2.0, 'Kūchaklī'),
 (2.0, 'Az Zubayr'),
 (2.0, 'Al Harithah'),
 (2.0, 'Al Basrah')]

In [53]:
slovar = temp_dict
out = []

In [54]:
for ch in range(0, 10):
    maks = 0
    country = ''
    for i in slovar:
        if slovar[i] >= maks:
            maks = slovar[i]
            country = i
    out.append(country)
    slovar.pop(country)
print(out)

['Azadshahr', 'Abqaiq', 'Ad Dujayl', 'Khalis', 'Baghdad', 'Al Basrah', 'Al Harithah', 'Az Zubayr', 'Kūchaklī', 'Qarchak']

In [59]:
import json
from pprint import pprint
ct = {}
with open("weather_16 (1).json", "r", encoding = "utf-8") as read_file:
    data = json.load(read_file)
    for k in range(100):
        temp = data[k]['main']['temp_max'] - data[k]['main']['temp_min']
        city = data[k]['city']['name']
        c = {city: temp}
        ct.update(c)
        
sort = sorted(ct.items(), key=lambda x: x[1], reverse=True)

for i in sort:
    print(i[0], i[1])

Azadshahr 5.0
Qarchak 2.0
Kūchaklī 2.0
Protaras 1.329999999999984
Kahriz 1.0
Ḩeşār-e Sefīd 1.0
Jilib 0.0
Kismaayo 0.0
Eyl 0.0
Mogadishu 0.0
Ceerigaabo 0.0
Beledweyne 0.0
Baydhabo 0.0
Istgah-e Garmsar 0.0
Ceeldheer 0.0
Jawhar 0.0
Khorram Darreh 0.0
Nurabad 0.0
Gobolka Jubbada Dhexe 0.0
Yarīm 0.0
Hobyo 0.0
As Suwayda 0.0
Ar Rawnah 0.0
Ash Shihr 0.0
Cadale 0.0
Gobolka Hiiraan 0.0
Behjatābād 0.0
Doon 0.0
Abs 0.0
Behelidle 0.0
Majzar 0.0
Cheli Gu 0.0
Mahaddayweyne 0.0
Laasqoray 0.0
Najd al Jumai 0.0
Suq ar Rabu 0.0
Gobolka Galguduud 0.0
Dahasuways 0.0
Sahar 0.0
El Ad 0.0
Gobolka Mudug 0.0
Shahrīār Kandeh 0.0
Muḩāfaz̧at Şa‘dah 0.0
Al Ghaylah 0.0
Al Jabin 0.0
Hajjah 0.0
Somalia 0.0
Ravīndūzaq 0.0
Ceek 0.0
Bidbadah 0.0
Ta‘izz 0.0
Gobolka Woqooyi Galbeed 0.0
Kalāteh-ye Dowlat 0.0
Al Anan 0.0
Cadayo 0.0
As Sawarah as Sughra 0.0
El Dubat 0.0
Republic of Rwanda 0.0
Dhi as Sufal 0.0
Manwakh 0.0
Mawza 0.0
Bereeda 0.0
Bayt al Faqih 0.0
Dīgāleh 0.0
Milah 0.0
Māmā’ī 0.0
Ma'rib 0.0
Az Zahir 0.0
Qishn 0.0
Usaylan 0.0
Al Jawl 0.0
Bajil 0.0
Marib City 0.0
Mawiyah 0.0
Lawdar 0.0
Manakhah 0.0
Zīrjān 0.0
Zarajah 0.0
Sif 0.0
Shihan as Sufla 0.0
Rudum 0.0
Oodweyne 0.0
Matwah 0.0
Judaydah 0.0
Kuhlan Afar 0.0
Ţālesh Maḩalleh 0.0
Mafhaq 0.0
Dalooldho 0.0
Al Malahit 0.0
Qabāghlū 0.0
Ariqah 0.0
Mabar 0.0
Gobolka Nugaal 0.0
Sah 0.0
Qaloocan 0.0
Mustaba 0.0
Taglag 0.0
Waajid 0.0
Wadarah 0.0
Dawran 0.0

In [61]:
sort[:10]

[('Azadshahr', 5.0),
 ('Qarchak', 2.0),
 ('Kūchaklī', 2.0),
 ('Protaras', 1.329999999999984),
 ('Kahriz', 1.0),
 ('Ḩeşār-e Sefīd', 1.0),
 ('Jilib', 0.0),
 ('Kismaayo', 0.0),
 ('Eyl', 0.0),
 ('Mogadishu', 0.0)]

Не забудьте про мониторинг! https://clck.ru/dX97i
<img src = 'http://disk.yandex.net/qr/?clean=1&text=https://clck.ru/dX97i' />